In [1]:
import pandas as pd
import numpy as np

## Checking arrangement of columns

In [5]:
df_p = pd.read_csv('TrainData_Processed.csv', index_col=[0])
df_p.head()

,Price,Levy,Prod. year,Leather interior,Engine volume,Mileage,Cylinders,Airbags,Turbo,Mileage_BIN,EngineVolume_BIN,Manufacturer,Model,Category,Fuel type,Gear box type,Drive wheels,Doors,Wheel,Color
0,9.497622,1399.0,2010,1,3.41,186005.0,6.0,12,0,5.0,4.0,21.0,1180.0,4.0,2.0,0.0,0.0,1.0,0.0,12.0
1,9.718422,1018.0,2011,0,3.00,192000.0,6.0,8,0,5.0,4.0,5.0,632.0,4.0,5.0,2.0,0.0,1.0,0.0,1.0
2,9.043932,0.0,2006,0,1.30,200000.0,4.0,2,0,5.0,0.0,14.0,656.0,3.0,5.0,3.0,1.0,1.0,1.0,1.0
3,8.190632,862.0,2011,1,2.50,168966.0,4.0,0,0,4.0,3.0,11.0,635.0,4.0,2.0,0.0,0.0,1.0,0.0,14.0
4,9.369564,446.0,2014,1,1.30,91901.0,4.0,4,0,2.0,0.0,14.0,656.0,3.0,5.0,0.0,1.0,1.0,0.0,12.0

In [7]:
df_r = pd.read_csv('TrainData_Raw.csv', index_col=[0])
df_r.head()

,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Turbo
0,13328,1399.0,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005.0,6.0,Automatic,4x4,04-May,Left wheel,Silver,12,0
1,16621,1018.0,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3.0,192000.0,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8,0
2,8467,0.0,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000.0,4.0,Variator,Front,04-May,Right-hand drive,Black,2,0
3,3607,862.0,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966.0,4.0,Automatic,4x4,04-May,Left wheel,White,0,0
4,11726,446.0,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901.0,4.0,Automatic,Front,04-May,Left wheel,Silver,4,0